[build]
functions = "./functions"

[[redirects]]
from = "/graphql/*"
to = "/.netlify/functions/github/:splat"
status = 200
force = true

[[redirects]]
from = "/api/v4/profile/activity/*"
to = "/.netlify/functions/hackthebox/:splat"
status = 200
force = true

[[redirects]]
from = "/api/user/activity-events/*"
to = "/.netlify/functions/tryhackme/:splat"
status = 200
force = true

[[redirects]]
from = "/api/v2/dashboard/annual-learning/*"
to = "/.netlify/functions/inflearn/:splat"
status = 200
force = true