[build]
functions = "./functions"

[[redirects]]
from = "/graphql/*"
to = "/.netlify/functions/github/:splat"
status = 200
force = true

[[redirects]]
from = "/api/v4/profile/activity/*"
to = "/.netlify/functions/hackthebox/:splat"
status = 200
force = true